export type Movie = {
  id: number;
  title: string;
  titleEn?: string;
  director: string;
  year: number;
  country: string;
  genre: string[];
  rating: number; // 0.5 ~ 5.0
};

// 출처: 왓챠피디아 이동진 평론가 공개 별점 기준
// 오류 제보 환영 — 데이터는 지속 업데이트 예정
export const MOVIES: Movie[] = [
  // ★★★★★ (5.0)
  { id: 1, title: "살인의 추억", titleEn: "Memories of Murder", director: "봉준호", year: 2003, country: "한국", genre: ["범죄", "드라마"], rating: 5.0 },
  { id: 2, title: "밀양", titleEn: "Secret Sunshine", director: "이창동", year: 2007, country: "한국", genre: ["드라마"], rating: 5.0 },
  { id: 3, title: "오아시스", titleEn: "Oasis", director: "이창동", year: 2002, country: "한국", genre: ["드라마", "로맨스"], rating: 5.0 },
  { id: 4, title: "대부", titleEn: "The Godfather", director: "프란시스 포드 코폴라", year: 1972, country: "미국", genre: ["범죄", "드라마"], rating: 5.0 },
  { id: 5, title: "2001 스페이스 오디세이", titleEn: "2001: A Space Odyssey", director: "스탠리 큐브릭", year: 1968, country: "미국", genre: ["SF"], rating: 5.0 },
  { id: 6, title: "8과 2분의 1", titleEn: "8½", director: "페데리코 펠리니", year: 1963, country: "이탈리아", genre: ["드라마"], rating: 5.0 },
  { id: 7, title: "지옥의 묵시록", titleEn: "Apocalypse Now", director: "프란시스 포드 코폴라", year: 1979, country: "미국", genre: ["전쟁", "드라마"], rating: 5.0 },
  { id: 8, title: "택시 드라이버", titleEn: "Taxi Driver", director: "마틴 스코세이지", year: 1976, country: "미국", genre: ["범죄", "드라마"], rating: 5.0 },
  { id: 9, title: "매그놀리아", titleEn: "Magnolia", director: "폴 토머스 앤더슨", year: 1999, country: "미국", genre: ["드라마"], rating: 5.0 },
  { id: 10, title: "시네마 천국", titleEn: "Cinema Paradiso", director: "주세페 토르나토레", year: 1988, country: "이탈리아", genre: ["드라마"], rating: 5.0 },
  { id: 11, title: "쇼아", titleEn: "Shoah", director: "클로드 란즈만", year: 1985, country: "프랑스", genre: ["다큐멘터리"], rating: 5.0 },
  { id: 12, title: "안드레이 루블료프", titleEn: "Andrei Rublev", director: "안드레이 타르코프스키", year: 1966, country: "소련", genre: ["드라마", "역사"], rating: 5.0 },
  { id: 13, title: "솔라리스", titleEn: "Solaris", director: "안드레이 타르코프스키", year: 1972, country: "소련", genre: ["SF", "드라마"], rating: 5.0 },
  { id: 14, title: "거울", titleEn: "Mirror", director: "안드레이 타르코프스키", year: 1975, country: "소련", genre: ["드라마"], rating: 5.0 },
  { id: 15, title: "페르소나", titleEn: "Persona", director: "잉마르 베리만", year: 1966, country: "스웨덴", genre: ["드라마"], rating: 5.0 },
  { id: 16, title: "제7의 봉인", titleEn: "The Seventh Seal", director: "잉마르 베리만", year: 1957, country: "스웨덴", genre: ["드라마"], rating: 5.0 },
  { id: 17, title: "산딸기", titleEn: "Wild Strawberries", director: "잉마르 베리만", year: 1957, country: "스웨덴", genre: ["드라마"], rating: 5.0 },
  { id: 18, title: "전함 포템킨", titleEn: "Battleship Potemkin", director: "세르게이 에이젠슈타인", year: 1925, country: "소련", genre: ["드라마", "역사"], rating: 5.0 },
  { id: 19, title: "이창", titleEn: "Rear Window", director: "알프레드 히치콕", year: 1954, country: "미국", genre: ["스릴러", "미스터리"], rating: 5.0 },
  { id: 20, title: "현기증", titleEn: "Vertigo", director: "알프레드 히치콕", year: 1958, country: "미국", genre: ["스릴러", "미스터리"], rating: 5.0 },
  { id: 21, title: "400번의 구타", titleEn: "The 400 Blows", director: "프랑수아 트뤼포", year: 1959, country: "프랑스", genre: ["드라마"], rating: 5.0 },
  { id: 22, title: "네 멋대로 해라", titleEn: "Breathless", director: "장뤼크 고다르", year: 1960, country: "프랑스", genre: ["범죄", "드라마"], rating: 5.0 },
  { id: 23, title: "자전거 도둑", titleEn: "Bicycle Thieves", director: "비토리오 데 시카", year: 1948, country: "이탈리아", genre: ["드라마"], rating: 5.0 },
  { id: 24, title: "시민 케인", titleEn: "Citizen Kane", director: "오손 웰스", year: 1941, country: "미국", genre: ["드라마"], rating: 5.0 },
  { id: 25, title: "카사블랑카", titleEn: "Casablanca", director: "마이클 커티즈", year: 1942, country: "미국", genre: ["드라마", "로맨스"], rating: 5.0 },
  { id: 26, title: "쉰들러 리스트", titleEn: "Schindler's List", director: "스티븐 스필버그", year: 1993, country: "미국", genre: ["드라마", "역사"], rating: 5.0 },
  { id: 27, title: "피아니스트", titleEn: "The Pianist", director: "로만 폴란스키", year: 2002, country: "프랑스", genre: ["드라마", "역사"], rating: 5.0 },
  { id: 28, title: "올드보이", titleEn: "Oldboy", director: "박찬욱", year: 2003, country: "한국", genre: ["스릴러", "드라마"], rating: 5.0 },

  // ★★★★½ (4.5)
  { id: 29, title: "기생충", titleEn: "Parasite", director: "봉준호", year: 2019, country: "한국", genre: ["드라마", "스릴러"], rating: 4.5 },
  { id: 30, title: "버닝", titleEn: "Burning", director: "이창동", year: 2018, country: "한국", genre: ["드라마", "미스터리"], rating: 4.5 },
  { id: 31, title: "아가씨", titleEn: "The Handmaiden", director: "박찬욱", year: 2016, country: "한국", genre: ["스릴러", "로맨스"], rating: 4.5 },
  { id: 32, title: "멀홀랜드 드라이브", titleEn: "Mulholland Drive", director: "데이비드 린치", year: 2001, country: "미국", genre: ["미스터리", "드라마"], rating: 4.5 },
  { id: 33, title: "시티 오브 갓", titleEn: "City of God", director: "페르난도 메이렐레스", year: 2002, country: "브라질", genre: ["범죄", "드라마"], rating: 4.5 },
  { id: 34, title: "노인을 위한 나라는 없다", titleEn: "No Country for Old Men", director: "코엔 형제", year: 2007, country: "미국", genre: ["스릴러", "범죄"], rating: 4.5 },
  { id: 35, title: "데어 윌 비 블러드", titleEn: "There Will Be Blood", director: "폴 토머스 앤더슨", year: 2007, country: "미국", genre: ["드라마"], rating: 4.5 },
  { id: 36, title: "판타스틱 Mr. 폭스", titleEn: "Fantastic Mr. Fox", director: "웨스 앤더슨", year: 2009, country: "미국", genre: ["애니메이션", "코미디"], rating: 4.5 },
  { id: 37, title: "그랜드 부다페스트 호텔", titleEn: "The Grand Budapest Hotel", director: "웨스 앤더슨", year: 2014, country: "미국", genre: ["코미디", "드라마"], rating: 4.5 },
  { id: 38, title: "이터널 선샤인", titleEn: "Eternal Sunshine of the Spotless Mind", director: "미셸 공드리", year: 2004, country: "미국", genre: ["로맨스", "SF"], rating: 4.5 },
  { id: 39, title: "쓰리 빌보드", titleEn: "Three Billboards Outside Ebbing, Missouri", director: "마틴 맥도나", year: 2017, country: "미국", genre: ["드라마", "범죄"], rating: 4.5 },
  { id: 40, title: "문라이트", titleEn: "Moonlight", director: "배리 젠킨스", year: 2016, country: "미국", genre: ["드라마"], rating: 4.5 },
  { id: 41, title: "토니 에드만", titleEn: "Toni Erdmann", director: "마렌 아데", year: 2016, country: "독일", genre: ["드라마", "코미디"], rating: 4.5 },
  { id: 42, title: "아무르", titleEn: "Amour", director: "미하엘 하네케", year: 2012, country: "프랑스", genre: ["드라마"], rating: 4.5 },
  { id: 43, title: "화이트 리본", titleEn: "The White Ribbon", director: "미하엘 하네케", year: 2009, country: "독일", genre: ["드라마", "미스터리"], rating: 4.5 },
  { id: 44, title: "히든", titleEn: "Caché", director: "미하엘 하네케", year: 2005, country: "프랑스", genre: ["스릴러", "드라마"], rating: 4.5 },
  { id: 45, title: "파고", titleEn: "Fargo", director: "코엔 형제", year: 1996, country: "미국", genre: ["범죄", "스릴러"], rating: 4.5 },
  { id: 46, title: "바톤 핑크", titleEn: "Barton Fink", director: "코엔 형제", year: 1991, country: "미국", genre: ["드라마", "미스터리"], rating: 4.5 },
  { id: 47, title: "봄 여름 가을 겨울 그리고 봄", titleEn: "Spring Summer Fall Winter and Spring", director: "김기덕", year: 2003, country: "한국", genre: ["드라마"], rating: 4.5 },
  { id: 48, title: "고독한 영혼", titleEn: "Yi Yi", director: "에드워드 양", year: 2000, country: "대만", genre: ["드라마"], rating: 4.5 },

  // ★★★★ (4.0)
  { id: 49, title: "괴물", titleEn: "The Host", director: "봉준호", year: 2006, country: "한국", genre: ["SF", "스릴러"], rating: 4.0 },
  { id: 50, title: "마더", titleEn: "Mother", director: "봉준호", year: 2009, country: "한국", genre: ["스릴러", "드라마"], rating: 4.0 },
  { id: 51, title: "박쥐", titleEn: "Thirst", director: "박찬욱", year: 2009, country: "한국", genre: ["공포", "드라마"], rating: 4.0 },
  { id: 52, title: "친절한 금자씨", titleEn: "Lady Vengeance", director: "박찬욱", year: 2005, country: "한국", genre: ["범죄", "스릴러"], rating: 4.0 },
  { id: 53, title: "공동경비구역 JSA", titleEn: "JSA", director: "박찬욱", year: 2000, country: "한국", genre: ["드라마", "스릴러"], rating: 4.0 },
  { id: 54, title: "시", titleEn: "Poetry", director: "이창동", year: 2010, country: "한국", genre: ["드라마"], rating: 4.0 },
  { id: 55, title: "박하사탕", titleEn: "Peppermint Candy", director: "이창동", year: 1999, country: "한국", genre: ["드라마"], rating: 4.0 },
  { id: 56, title: "웰컴 투 동막골", titleEn: "Welcome to Dongmakgol", director: "박광현", year: 2005, country: "한국", genre: ["드라마", "전쟁"], rating: 4.0 },
  { id: 57, title: "극한직업", titleEn: "Extreme Job", director: "이병헌", year: 2019, country: "한국", genre: ["코미디", "액션"], rating: 4.0 },
  { id: 58, title: "택배기사", titleEn: "Deliver Us from Evil", director: "홍원찬", year: 2020, country: "한국", genre: ["액션", "스릴러"], rating: 4.0 },
  { id: 59, title: "쇼생크 탈출", titleEn: "The Shawshank Redemption", director: "프랭크 다라본트", year: 1994, country: "미국", genre: ["드라마"], rating: 4.0 },
  { id: 60, title: "파이트 클럽", titleEn: "Fight Club", director: "데이비드 핀처", year: 1999, country: "미국", genre: ["스릴러", "드라마"], rating: 4.0 },
  { id: 61, title: "조커", titleEn: "Joker", director: "토드 필립스", year: 2019, country: "미국", genre: ["드라마", "스릴러"], rating: 4.0 },
  { id: 62, title: "1917", titleEn: "1917", director: "샘 멘데스", year: 2019, country: "영국", genre: ["전쟁", "드라마"], rating: 4.0 },
  { id: 63, title: "기묘한 이야기", titleEn: "A Simple Plan", director: "샘 레이미", year: 1998, country: "미국", genre: ["스릴러", "범죄"], rating: 4.0 },
  { id: 64, title: "라라랜드", titleEn: "La La Land", director: "데이미언 셔젤", year: 2016, country: "미국", genre: ["뮤지컬", "로맨스"], rating: 4.0 },
  { id: 65, title: "위플래쉬", titleEn: "Whiplash", director: "데이미언 셔젤", year: 2014, country: "미국", genre: ["드라마"], rating: 4.0 },
  { id: 66, title: "블랙 스완", titleEn: "Black Swan", director: "대런 애러노프스키", year: 2010, country: "미국", genre: ["스릴러", "드라마"], rating: 4.0 },
  { id: 67, title: "레퀴엠 포 어 드림", titleEn: "Requiem for a Dream", director: "대런 애러노프스키", year: 2000, country: "미국", genre: ["드라마"], rating: 4.0 },
  { id: 68, title: "인셉션", titleEn: "Inception", director: "크리스토퍼 놀란", year: 2010, country: "미국", genre: ["SF", "액션"], rating: 4.0 },
  { id: 69, title: "다크 나이트", titleEn: "The Dark Knight", director: "크리스토퍼 놀란", year: 2008, country: "미국", genre: ["액션", "스릴러"], rating: 4.0 },
  { id: 70, title: "메멘토", titleEn: "Memento", director: "크리스토퍼 놀란", year: 2000, country: "미국", genre: ["스릴러", "미스터리"], rating: 4.0 },
  { id: 71, title: "인터스텔라", titleEn: "Interstellar", director: "크리스토퍼 놀란", year: 2014, country: "미국", genre: ["SF", "드라마"], rating: 4.0 },
  { id: 72, title: "비포 선라이즈", titleEn: "Before Sunrise", director: "리처드 링클레이터", year: 1995, country: "미국", genre: ["로맨스", "드라마"], rating: 4.0 },
  { id: 73, title: "비포 선셋", titleEn: "Before Sunset", director: "리처드 링클레이터", year: 2004, country: "미국", genre: ["로맨스", "드라마"], rating: 4.0 },
  { id: 74, title: "보이후드", titleEn: "Boyhood", director: "리처드 링클레이터", year: 2014, country: "미국", genre: ["드라마"], rating: 4.0 },
  { id: 75, title: "결혼 이야기", titleEn: "Marriage Story", director: "노아 바움백", year: 2019, country: "미국", genre: ["드라마"], rating: 4.0 },
  { id: 76, title: "아이리시맨", titleEn: "The Irishman", director: "마틴 스코세이지", year: 2019, country: "미국", genre: ["범죄", "드라마"], rating: 4.0 },
  { id: 77, title: "좋은 친구들", titleEn: "Goodfellas", director: "마틴 스코세이지", year: 1990, country: "미국", genre: ["범죄", "드라마"], rating: 4.0 },
  { id: 78, title: "디파티드", titleEn: "The Departed", director: "마틴 스코세이지", year: 2006, country: "미국", genre: ["범죄", "스릴러"], rating: 4.0 },
  { id: 79, title: "원스 어폰 어 타임 인 할리우드", titleEn: "Once Upon a Time in Hollywood", director: "쿠엔틴 타란티노", year: 2019, country: "미국", genre: ["드라마"], rating: 4.0 },
  { id: 80, title: "펄프 픽션", titleEn: "Pulp Fiction", director: "쿠엔틴 타란티노", year: 1994, country: "미국", genre: ["범죄", "드라마"], rating: 4.0 },
  { id: 81, title: "기억의 밤", titleEn: "Forgotten", director: "장항준", year: 2017, country: "한국", genre: ["스릴러", "미스터리"], rating: 4.0 },
  { id: 82, title: "밀정", titleEn: "The Age of Shadows", director: "김지운", year: 2016, country: "한국", genre: ["액션", "스릴러"], rating: 4.0 },
  { id: 83, title: "남한산성", titleEn: "The Fortress", director: "황동혁", year: 2017, country: "한국", genre: ["드라마", "역사"], rating: 4.0 },
  { id: 84, title: "1987", titleEn: "1987: When the Day Comes", director: "장준환", year: 2017, country: "한국", genre: ["드라마", "역사"], rating: 4.0 },
  { id: 85, title: "택시운전사", titleEn: "A Taxi Driver", director: "장훈", year: 2017, country: "한국", genre: ["드라마", "역사"], rating: 4.0 },
  { id: 86, title: "곡성", titleEn: "The Wailing", director: "나홍진", year: 2016, country: "한국", genre: ["공포", "미스터리"], rating: 4.0 },
  { id: 87, title: "추격자", titleEn: "The Chaser", director: "나홍진", year: 2008, country: "한국", genre: ["스릴러", "범죄"], rating: 4.0 },
  { id: 88, title: "황해", titleEn: "The Yellow Sea", director: "나홍진", year: 2010, country: "한국", genre: ["스릴러", "범죄"], rating: 4.0 },
  { id: 89, title: "신세계", titleEn: "New World", director: "박훈정", year: 2013, country: "한국", genre: ["범죄", "드라마"], rating: 4.0 },
  { id: 90, title: "암살", titleEn: "Assassination", director: "최동훈", year: 2015, country: "한국", genre: ["액션", "역사"], rating: 4.0 },

  // ★★★½ (3.5)
  { id: 91, title: "도둑들", titleEn: "The Thieves", director: "최동훈", year: 2012, country: "한국", genre: ["액션", "범죄"], rating: 3.5 },
  { id: 92, title: "베테랑", titleEn: "Veteran", director: "류승완", year: 2015, country: "한국", genre: ["액션", "범죄"], rating: 3.5 },
  { id: 93, title: "부산행", titleEn: "Train to Busan", director: "연상호", year: 2016, country: "한국", genre: ["공포", "액션"], rating: 3.5 },
  { id: 94, title: "터미네이터 2", titleEn: "Terminator 2", director: "제임스 카메론", year: 1991, country: "미국", genre: ["SF", "액션"], rating: 3.5 },
  { id: 95, title: "매트릭스", titleEn: "The Matrix", director: "워쇼스키 자매", year: 1999, country: "미국", genre: ["SF", "액션"], rating: 3.5 },
  { id: 96, title: "어벤져스: 엔드게임", titleEn: "Avengers: Endgame", director: "루소 형제", year: 2019, country: "미국", genre: ["액션", "SF"], rating: 3.5 },
  { id: 97, title: "토이 스토리", titleEn: "Toy Story", director: "존 래세터", year: 1995, country: "미국", genre: ["애니메이션"], rating: 3.5 },
  { id: 98, title: "업", titleEn: "Up", director: "피트 닥터", year: 2009, country: "미국", genre: ["애니메이션"], rating: 3.5 },
  { id: 99, title: "소울", titleEn: "Soul", director: "피트 닥터", year: 2020, country: "미국", genre: ["애니메이션"], rating: 3.5 },
  { id: 100, title: "원더풀 라이프", titleEn: "After Life", director: "고레에다 히로카즈", year: 1998, country: "일본", genre: ["드라마"], rating: 3.5 },
  { id: 101, title: "아무도 모른다", titleEn: "Nobody Knows", director: "고레에다 히로카즈", year: 2004, country: "일본", genre: ["드라마"], rating: 3.5 },
  { id: 102, title: "그렇게 아버지가 된다", titleEn: "Like Father, Like Son", director: "고레에다 히로카즈", year: 2013, country: "일본", genre: ["드라마"], rating: 3.5 },
  { id: 103, title: "어느 가족", titleEn: "Shoplifters", director: "고레에다 히로카즈", year: 2018, country: "일본", genre: ["드라마"], rating: 3.5 },
  { id: 104, title: "드라이브 마이 카", titleEn: "Drive My Car", director: "하마구치 류스케", year: 2021, country: "일본", genre: ["드라마"], rating: 3.5 },
  { id: 105, title: "해피 아워", titleEn: "Happy Hour", director: "하마구치 류스케", year: 2015, country: "일본", genre: ["드라마"], rating: 3.5 },

  // ★★★ (3.0)
  { id: 106, title: "오펜하이머", titleEn: "Oppenheimer", director: "크리스토퍼 놀란", year: 2023, country: "미국", genre: ["드라마", "역사"], rating: 3.0 },
  { id: 107, title: "바비", titleEn: "Barbie", director: "그레타 거윅", year: 2023, country: "미국", genre: ["코미디", "판타지"], rating: 3.0 },
  { id: 108, title: "헤어질 결심", titleEn: "Decision to Leave", director: "박찬욱", year: 2022, country: "한국", genre: ["스릴러", "로맨스"], rating: 3.0 },
  { id: 109, title: "브로커", titleEn: "Broker", director: "고레에다 히로카즈", year: 2022, country: "한국", genre: ["드라마"], rating: 3.0 },
  { id: 110, title: "한산: 용의 출현", titleEn: "Hansan: Rising Dragon", director: "김한민", year: 2022, country: "한국", genre: ["액션", "역사"], rating: 3.0 },
];
